services: 
  mongo: 
    image: mirror.gcr.io/library/mongo:8 
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin_user  
      MONGO_INITDB_ROOT_PASSWORD: web3 
    ports: 
      - "27017:27017" 
    networks: 
      - mongo-network 
 
  calculadora: 
    image: ghcr.io/bearozz/web_iii_practica1-back:latest 
    volumes: 
      - ./backend:/app 
    ports: 
      - "8089:8000"
    networks:
      - mongo-network

  frontend:
    image: ghcr.io/bearozz/web_iii_practica1-front:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - calculadora
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

