name: Build and Push Docker Image

#cuando
on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'

#qué
jobs:
  #qué entrno o con qué
  build:
    runs-on: ubuntu-latest

    #permisos necesarios
    permissions:
      contents: read
      packages: write #necesario para subir a GHCR

    #pasos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi
      
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.TAG }} ./backend

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}