name: Build and Push Docker Image Front

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Verifica si hubo cambios en frontend/
      - name: Check if frontend changed
        id: frontend-check
        run: |
          if ! git diff --name-only HEAD~1 HEAD | grep -q '^frontend/'; then
            echo "No frontend changes detected. Skipping build."
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Stop if no frontend changes
        if: env.skip == 'true'
        run: exit 0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_LOWER}" >> $GITHUB_ENV

          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image (Frontend)
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}-front:${{ env.TAG }} ./frontend

      - name: Push Docker image (Frontend)
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}-front:${{ env.TAG }}
